// deno run --allow-net --allow-write fetch_data.js --key [COVALENT_API_KEY]
// get covalent API key from https://www.covalenthq.com/platform/#/auth/register/
import { parse } from 'https://deno.land/std/flags/mod.ts'
import { Timeout } from "https://deno.land/x/timeout/mod.ts"

import { getTimeStamp, getTimeTag } from '../src/helpers/formatDate.js'
import { ETH_BRIDGE_CONTRACTS } from '../src/data/bridge_contracts.js'
const { args, exit, writeTextFileSync } = Deno

// parse args
const { key = '', quote = 'eth' } = parse(args)
if (!key) {
  console.error(`Please provide covalent API with --key\n
  ex: deno run --allow-net --allow-write fetch_data.js --key [COVALENT_API_KEY]`)
  exit(1)
}

// form the query
const options = {
  key: key,
  'quote-currency': quote,
}
const params = Object.keys(options).map(key => `${encodeURIComponent(key)}=${encodeURIComponent(options[key])}`).join('&')

// collect contracts
const addrInfo = {}
Array.from(new Set(
  (Object.keys(ETH_BRIDGE_CONTRACTS))
    .map(project => ETH_BRIDGE_CONTRACTS[project]?.bridges.map(entry => {
      addrInfo[entry.address] = {project: project, name: entry.name || '', chainId: entry.chainId}
      return entry.address
    }))
    .flat(1)
))
// console.log('contracts %O', addrInfo)

const getBalanceURL = (address, chainId = 1) => `https://api.covalenthq.com/v1/${chainId}/address/${address}/balances_v2/?${params}`

// write file
function writeJson(data, pathSubfix) {
  try {
    const timestamp = getTimeStamp()
    const today = getTimeTag('today', timestamp)
    const yesterday = getTimeTag('yesterday', timestamp)
    const filePath = pathSubfix ? `src/data/${today}-${pathSubfix}.json` : `src/data/${today}.json`
    console.log('write to', filePath)
    writeTextFileSync(filePath, JSON.stringify(data))

    const dataPath = `src/data/data.js`
    const content = `// DONT CHANGE! this file is auto generated by scripts/fetch_data.js
import todayData from './${today}.json'
import yesterdayData from './${yesterday}.json'
export const timestamp = '${timestamp}'
export const today = todayData
export const yesterday = yesterdayData
export default todayData
`
    writeTextFileSync(dataPath, content)
    return "Written to " + dataPath

  } catch (e) {
    console.error(e.message)
  }
}

// main
async function main() {
  try {
    console.log('Get ethereum price...')
    const ethPrice = await fetch('https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd')
    const collectData = await ethPrice.json()

    const addrs = Object.keys(addrInfo)
    for (const addr of addrs) {
      // multi-chain support
      const link = getBalanceURL(addr, addrInfo[addr].chainId)
      const res = await fetch(link)
      const data = await res.json()

      const proj = addrInfo[addr].project
      console.log('process ', proj, addrInfo[addr].name)
      if (!collectData[proj]) {
        collectData[proj] = {}
        collectData[proj].bridges = [data.data]
      } else {
        collectData[proj].bridges.push(data.data)
      }
      // to not brute the API limit
      await Timeout.wait(200)
    }

    // calc tvl per project
    (Object.keys(ETH_BRIDGE_CONTRACTS))
      .map(proj => {
        let tvl = 0
        console.log('tvl of ', proj)
        collectData[proj].bridges.map(bridge => bridge.items.map(item => {
          tvl += item.quote
          return ''
        }))
        collectData[proj].tvl = tvl
        return ''
      })

    writeJson(collectData)
  } catch (e) {
    console.error(e.message)
  }
}

main()
